[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GmSSL"
authors = [{name = "GmSSL", email = "zhaopku09@gmail.com"}]
dynamic = ["version", "description"]
